name: Test Secrets Only

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret Access
        run: |
          echo "Testing secret access..."
          echo "AWS_ACCESS_KEY_ID exists: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY exists: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
          
          if [ -n "$AWS_ACCESS_KEY_ID" ]; then
            echo "✅ AWS_ACCESS_KEY_ID found (length: ${#AWS_ACCESS_KEY_ID})"
            echo "First 8 chars: ${AWS_ACCESS_KEY_ID:0:8}"
          else
            echo "❌ AWS_ACCESS_KEY_ID not found"
          fi
          
          if [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "✅ AWS_SECRET_ACCESS_KEY found (length: ${#AWS_SECRET_ACCESS_KEY})"
            echo "First 8 chars: ${AWS_SECRET_ACCESS_KEY:0:8}"
          else
            echo "❌ AWS_SECRET_ACCESS_KEY not found"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Test AWS CLI
        run: |
          echo "Testing AWS CLI..."
          aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
